AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: >-
      Select a VPC that allows instances to access the Internet. Select same VPC
      in which LoadBalancer was created.
  SubnetId:
    Type: 'List<AWS::EC2::Subnet::Id>'

  DesiredCapacity:
    Type: Number
    Default: 1
    Description: Number of instances to launch in your ECS cluster.
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: test-cluster
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: test-log-group

Outputs:
  ClusterNameExport:
    Value: !Ref Cluster
    Export:
      Name: !Sub ${AWS::StackName}-Cluster

      
